### ISSUE TITLE
Instant crash after startup

### ISSUE THREAD

**Issue by ZweiEuro** [Linux74656/SpaceEngineersLinuxPatches#36] opened 2020-07-10 12:59 UTC
I have tried this patch and have searched around some more. 
Some people on the ProtonDB also report to have this issue but I don't see it anywhere in here.
https://www.protondb.com/app/244850
In short it crashes instantly, I am attaching the log since you guys have way more experience

 then me in reading stuff like this.

[SpaceEngineers_20200710_145947447.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/4903209/SpaceEngineers_20200710_145947447.log)

**Comment by Linux74656** [comment] 2020-07-17 06:22
This looks like a dotnet issue.
Try manually installing dotnet ontop of your existing prefix.

Something like this (ensure this is the right prefix):
`WINEPREFIX=\home\zweieuro\.local\share\Steam\steamapps\common\SpaceEngineers\Bin64 winetricks --force -q dotnet48`

**Comment by Linux74656** [comment] 2021-02-02 13:53
I will close this as i assume the issue is resolved.

**Closed as completed by Linux74656** 2021-02-02 13:53 UTC
